version: '1'

services:
  db:
    image: postgres:16.2-alpine3.19
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: root
      POSTGRES_DB: stocksdb
    ports:
      - "5432:5432"